### ISSUE TITLE
MRI.jl no longer present

### ISSUE THREAD

**Issue by hjbockholt** [korbinian90/CLEARSWI.jl#4]
Hi, in your instructions for using SWI, you indicate using MRI.jl but it looks like you have changed that name to MriResearchTools. Your Project and Manifest files on this project both indicate to use MRI as well as the instructions in your readme file.  Maybe consider changing this?
thanks!

**Comment by korbinian90** [comment]
Thanks! I will fix it soon.

I plan to completely update this package in the coming weeks and also rename it to ClearSwi.jl. We presented [CLEAR SWI](https://index.mirasmart.com/ISMRM2020/PDFfiles/3201.html) at the ISMRM and are currently publishing the corresponding paper.

**Comment by hjbockholt** [comment]
awesome, looking forward to the changes!

**Comment by korbinian90** [comment]
The package is updated now.
I still want to refactor and clean up some code and add some documentation, but it should work now
