### ISSUE TITLE
Error while running ClearSWI

### ISSUE THREAD

**Issue by tsantini** [korbinian90/CLEARSWI.jl#5]
Hello, I was reading your recent publication and decided to test your method in our 7T data (Siemens). The differences between my data and your test data are: 1) our data only have 2 echos; 2) our data include the whole brain; 3) we have different echo times.  Your test data runs fine but I'm getting the error below. I tested in both 2D and 3D GRE (the 3D GRE includes a high pass filter in the phase images while the 2D does not). I'm using julia version 1.6.1. To convert from Dicom to Nifti, I used the command `dcm2niix -m y .`. Please let me know if you have any suggestions. 

```
ERROR: LoadError: MethodError: no method matching to_dim(::Matrix{Int64}, ::Int64)

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  to_dim(::AbstractVector{T} where T, ::Int64) at /home/ts/.julia/packages/MriResearchTools/IJXp0/src/utility.jl:139
Stacktrace:
 [1] getcombinedphase(data::Data, options::Options, mask::BitArray{3})
   @ CLEARSWI ~/.julia/packages/CLEARSWI/bAFSt/src/phase_processing.jl:43
 [2] getswiphase(data::Data, options::Options)
   @ CLEARSWI ~/.julia/packages/CLEARSWI/bAFSt/src/phase_processing.jl:5
 [3] calculateSWI(data::Data, options::Options)
   @ CLEARSWI ~/.julia/packages/CLEARSWI/bAFSt/src/functions.jl:8
 [4] calculateSWI(data::Data)
   @ CLEARSWI ~/.julia/packages/CLEARSWI/bAFSt/src/functions.jl:7
 [5] top-level scope
   @ ~/210522-testing_clear_SWI/testing:12
in expression starting at /home/ts/210522-testing_clear_SWI/testing:12
```

Here is my script:
```
using CLEARSWI

TEs = [14 28] # change this to the Echo Time of your sequence. For multi-echoes, set a list of TE values, else set a list with a single TE value.
nifti_folder = "/home/ts/210522-testing_clear_SWI" # replace with path to your folder e.g. nifti_folder="/data/clearswi"
magfile = joinpath(nifti_folder, "mag.nii") # Path to the magnitude image in nifti format, must be .nii or .hdr
phasefile = joinpath(nifti_folder, "phase.nii") # Path to the phase image

mag = readmag(magfile);
phase = readphase(phasefile);
data = Data(mag, phase, mag.header, TEs);

swi = calculateSWI(data);
mip = createMIP(swi);

savenii(swi, "/home/ts/210522-testing_clear_SWI/swi"; header=mag.header) # change <outputpath> with the path where you want to save the reconstructed SWI
savenii(mip, "/home/ts/210522-testing_clear_SWI/mip"; header=mag.header)
```

**Comment by korbinian90** [comment]
Thank you for reporting this error. Looks like I messed up a compatibility... I'll try to debug it tomorrow

**Comment by korbinian90** [comment]
I don't have access to my computer to verify at the moment, but a first thing you could try is to put a comma in the definition of the echo times.
TEs = [14, 28]

[14 28] creates a matrix (row vector) and [14, 28] creates a standard vector (column vector).

I think with adding the comma it should work. Still, I will add support to [2 3] type vectors as it is confusing like it is now

**Comment by tsantini** [comment]
Thanks a lot, it works now!  Sorry, my bad, you were clear in your instructions regarding the comma. I'm just too used to other languages and I couldn't see the mistake. Congrats on your excellent work, it works beautifully in our data.
